baseurl: "/"
title: "Modelizacion Forestal SECF"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  #Name: "Conference name"
  #Description: "Conference description"
  #Date: "November 15"
  #Price: "Only $100" # If your event is free, just comment this line
  #Venue: "Coco Bongo"
  #Address: "Boulevard Kukulcan, 30"
  #City:  "CancÃºn"
  #State: "Quintana"
  #Images: ["/img/badge.jpg"]
  #GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - schedule
    - speakers
    - comite
    - location
    #- sponsors
    - registration
    #- partners

  # Titles which you can translate to other languages
  Titles:
    about: "La reunión"
    location: "Sede"
    speakers: "Ponentes Invitados"
    schedule: "Programa"
    comite: "Comité Organizador y Científico"
    sponsors: "Colaboran"
    #partners: "Colaboradores"
    registration: "Inscripción y documentación"

  # List of Sponsors
  Sponsors:
    - name: "CTFC"
      logo: "/img/logo_ctfc.jpg"
      url: "http://www.ctfc.cat"
    - name: "SECF"
      logo: "/img/logo_secf.jpg"
      url: "http://www.secforestales.org"

    - name: "UdL"
      logo: "/img/logo_udl.png"
      url: "http://www.udl.cat/ca/"

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/hugo.jpg"
      url: "https://gohugo.io"
    - name: "BrazilJS"
      logo: "/img/partner.png"
      url: "http://braziljs.org"

  # The entire schedule
  ScheduleDay1:
    - name: "Bienvenida/Recepción de participantes"
      time: "8h30"
    - name: "Inauguración de las jornadas"
      time: "9h00"
    
    
    - name: "Felipe Bravo"
      company: "iuFor-Universidad de Valladolid"
      photo: "img/FotoFelipeBravo.jpeg"
      link:
        href: "http://twitter.com/fbravo_sfm"
        text: "@fbravo_sfm"
      presentation:
        title: "Modelización Forestal. Un paseo del rodal al paisaje para tomar decisiones informadas comprendiendo la dinámica forestal"
        description: "Resumen a venir"
        time: "9h30"    
    
    - sesion: "Sesion I"
      description: "Modelización de la dinámica forestal y la distribución de especies en un contexto de cambio global"
    - name: "Presentaciones orales"
      time: "10h00"  
      description: "Sesión I"
    - name: "Pausa Café"
      coffee: "Break"
      time: "11h30"  

    - name: "Nuria Aquilué"
      company: "UQAM-CTFC"
      photo: "img/FotoNuriaAquilue.jpeg"
      presentation:
        title: "Modelizando el futuro de los paisajes forestales Mediterráneos: El reto de la integración"
        time: "12h00"
    - name: "Presentaciones orales"
      time: "12h30"  
      description: "Sesión I"

    - name: "Comida"
      time: "13h30"  
      
    - sesion: "Sesion II"
      description: "Modelización del crecimiento y la productividad forestal: nuevas técnicas y herramientas" 
      
    - name: "Rafael Calama"
      company: "INIA"
      photo: "img/FotoRafaCalama.jpeg"
      presentation:
        title: "¿Realmente necesitamos herramientas estadísticas tan complejas para construir modelos empíricos de apoyo a la gestión forestal?"
        time: "15h00"
 
    - name: "Presentaciones orales"
      time: "15h30" 
      description: "Sesión II"

    - name: "Pausa-café"
      time: "17h00" 
      
    - name: "Presentaciones breves/Sesión de posters"
      time: "17h30" 
      
  ScheduleDay2:

    - sesion: "Sesion III"
      description: "Modelización de procesos ecológicos e interacciones bosque-agua" 
          
    - name: "Miquel de Caceres"
      company: "CTFC"
      photo: "img/FotoMiqueldeCaceres.jpeg"
      presentation:
        title: "Modelización ecohidrológica en el bosque mediterráneo: escalas, procesos y retos"
        time: "9h00"

    - name: "Presentaciones orales"
      time: "9h30" 
      description: "Sesión III"
      
    - name: "Pausa-café"
      time: "11h00" 
      
    - name: "Presentaciones orales"
      time: "11h30" 
      description: "Sesión III (cont.)"

    - name: "Presentaciones breves/Sesión de posters"
      time: "12:30" 
      description: 
    
    - name: "Comida"
      time: "13h30"   
 
 
    - sesion: "Sesion IV"
      description: "Cuantificación, valoración y optimización de servicios ecosistémicos" 
               
    - name: "Elsa Varela"
      photo: "/img/FotoElsaVarela.jpeg"
      company: "CREDA-UPC-IRTA"
      presentation:
        title: "Valoración económica de servicios ecosistémicos: aplicación, resultados y limitaciones en el contexto forestal Mediterráneo"
        time: "15h00"
        
    - name: "Presentaciones orales"
      time: "15h30" 
      description: "Sesión IV "

    - name: "Pausa-café"
      time: "17h00"

    - name: "Mesa redonda"
      time: "17h30" 
      description: "Mesa redonda, conclusiones y clausura de las jornadas"

# List of Speakers
  Speakers:
    - name: "Felipe Bravo"
      company: "Universidad de Valladolid"
      photo: "/img/FotoFelipeBravo.jpeg"
      bio: "Catedrático de Universidad, Director del Instituto Universitario de Investigación en Gestión Forestal Sostenible. Presidente de la Sociedad Española de Ciencias Forestales. Su investigación se centra en la selvicultura, la dinámica forestal y la modelización del crecimiento y producción forestal "
      talk: "Modelización Forestal. Un paseo del rodal al paisaje para tomar decisiones informadas comprendiendo la dinámica forestal"
      website: "http://sostenible.palencia.uva.es/users/fbravo"
      sites:
       - name: "@fbravo_sfm"
         href: "https://twitter.com/fbravo_sfm"
         text: "@fbravo_sfm"
         
    - name: "Nuria Aquilué"
      company: "UQAM-InForest JRU (CTFC-CREAF)"
      photo: "/img/FotoNuriaAquilue.jpeg"
      bio: "Investigadora postdoctoral de la Université du Québec à Montreal (Canadá) y del Centre de Ciència i Tecnología Forestal de Catalunya. Su investigación se centra en cuantificar los efectos sobre los ecosistemas forestales de factores de cambio tanto naturales como antrópicos y de las interacciones espacio-temporales entre ellos, usando modelos dinámicos de paisaje aplicados a escalas regionales. "
      talk: "Modelizando el futuro de los paisajes forestales Mediterráneos: El reto de la integración"
      website: "http://www.cef-cfr.ca/index.php?n=Membres.NuriaAquilueJunyent"
      sites:
       - name: "Website"
         href: "http://www.cef-cfr.ca/index.php?n=Membres.NuriaAquilueJunyent"
         text: "Website"
         
    - name: "Rafael Calama"
      company: "Instituto Nacional de Investigaciones Agrarias"
      photo: "/img/FotoRafaCalama.jpeg"
      bio: "Científico Titular en el Departamento de Dinámica y Gestión Forestal del INIA-CIFOR, y profesor invitado de Modelización forestal en la Universidad de Valladolid. Especialista en modelización y gestión forestal. Su principal línea de investigación se centra en la modelización de los diferentes procesos asociados con la dinámica de los bosques Mediterráneos"
      talk: "¿Realmente necesitamos herramientas estadísticas tan complejas para construir modelos empíricos de apoyo a la gestión forestal?"
      website: "http://sostenible.palencia.uva.es/users/rcalama"
      sites:
       - name: "twitter"
         href: "https://twitter.com/rafacalama2"
         text: "@rafacalama2"

         
    - name: "Miquel de Cáceres"
      company: "Centre de Ciència i Tecnologia Forestal de Catalunya (CTFC)"
      photo: "/img/FotoMiqueldeCaceres.jpeg"
      bio: "Investigador del CTFC, responsable del grupo de Modelización de la Vegetación y adjunto a la dirección del Programa de Gestión Multifuncional del CTFC. Su investigación se centra en la modelización de la dinámica vegetal y las relaciones bosque-agua"
      talk: "Modelización ecohidrológica en el bosque mediterráneo: escalas, procesos y retos"
      website: "http://vegmod.ctfc.cat/"
      sites:

         
    - name: "Elsa Varela"
      company: "CREDA-UPC-IRTA"
      photo: "/img/FotoElsaVarela.jpeg"
      bio: "Investigadora en el IRTA y asociada a CREDA desde 2015. Su línea de investigación se centra en la valoración económica de servicios ecosistémicos y externalidades ambientales proporcionados por sistemas forestales y agrarios"
      talk: "Valoración económica de servicios ecosistémicos: aplicación, resultados y limitaciones en el contexto forestal Mediterráneo"
      website: "https://www.researchgate.net/profile/Elsa_Varela"



# Organizing Comitee
  Comite:
    - name: "Aitor Ameztegui"
      company: "Universitat de Lleida"
      photo: "/img/FotoAitorAmeztegui.jpg"
      bio: "Docente e Investigador en la Universitat de Lleida, e investigador asociado al Centre de Ciència i Tecnologia Forestal de Catalunya. Coordinador del grupo de trabajo de Modelización Forestal de la Sociedad Española de Ciencias Forestales. Su investigación se centra en la modelización de la dinámica forestal bajo distintos escenarios climáticos y de gestión. Director y Coordinador del Congreso"

    - name: "Andrés Bravo-Oviedo"
      company: "Museo Nacional de Ciencias Naturales - CSIC"
      photo: "/img/FotoAndresBravo2.jpg"
      bio: "Científico Titular en el Departamento de Biogeografía y Cambio Global del Museo Nacional de Ciencias Naturales (CSIC).  Co-coordinador del grupo de trabajo de Modelización Forestal de la Sociedad Española de Ciencias Forestales. Su investigación se engloba en tres ejes: gestión forestal en el contexto de sistemas socio-ecológicos, resiliencia y complejidad de sistemas forestales, y modelización de servicios ecosistémicos"
      
    - name: "Cristina Vega"
      company: "Universitat de Lleida"
      photo: "/img/FotoCristinaVega.jpeg"
      bio: "Profesora Titular de Universidad del Departamento de Ingeniería Agroforestal de la Universitat de Lleida. Investigadora Asociada al Centre de Ciència i Tecnologia Forestal de Catalunya. Su investigación se centra en la modelización del riesgo de incendios forestales y la planificación forestal a escala del paisaje"

    - name: "Antoni Trasobares"
      company: "Centre de Ciència i Tecnologia Forestal de Catalunya"
      photo: "/img/FotoAntoniTrasobares.jpg"
      bio: "Director del Centre de Ciència i Tecnologia Forestal de Catalunya, con amplia experiencia investigadora en la modelización del crecimiento de especies forestales."
 
    - name: "Lluís Coll"
      company: "Universitat de Lleida"
      photo: "/img/FotoLluisColl.jpeg"
      bio: "Profesor Agregado del Departamento de Ingeniería Agroforestal de la Universitat de Lleida e Investigador Asociado al Centre de Ciència i Tecnologia Forestal de Catalunya. Su investigación se centra en la comprensión del funcionamiento y dinámica del bosque y su aplicación a la gestión forestal."
 
    - name: "Assu Planas"
      company: "Centre de Ciència i Tecnologia Forestal de Catalunya"
      photo: "/img/FotoAssuPlanas.jpeg"
      bio: "Responsable de comunicación del Centre de Ciència i Tecnologia Forestal de Catalunya, con amplia experiencia en la organización de congresos y la elaboración de planes de comunicación de eventos similares."

# Scientific Comitee
  Scicom:
    - name: "Raquel Benavides"
      photo: "/img/FotoRaquelBenavides.jpeg"
      company: "Museo Nacional de Ciencias Naturales - CSIC"
    - name: "Juan A. Blanco"
      photo: "/img/FotoJuanBlanco.jpeg"
      company: "Universidad Pública de Navarra"
    - name: "Antonio del Campo"
      photo: "/img/FotoAntoniodelCampo.jpg"
      company: "Universitat Politécnica de València"
    - name: "Sonia Condés"
      photo: "/img/FotoSoniaCondes.jpeg"
      company: "Universidad Politécnica de Madrid"
    - name: "Olalla Díaz-Yañez"
      photo: "/img/FotoOlallaDiaz.jpeg"
      company: "University of Eastern Finland"
    - name: "Andrea Duane"
      photo: "/img/FotoAndreaDuane.jpg"
      company: "Centre de Ciència i Tecnologia Forestal de Catalunya (CTFC)"
    - name: "Raúl García-Valdés"
      photo: "/img/FotoRaulGarcia.jpeg"
      company: "Centre de Recerca en Ecologia i Aplicacions Forestals (CREAF)"
    - name: "Elena Górriz"
      photo: "/img/FotoElenaGorriz.jpeg"
      company: "EFIMED - CTFC"
    - name: "Santiago Martín-Alcón"
      photo: "/img/FotoSantiagoMartin.jpeg"
      company: "Agresta S Coop."
    - name: "Sergio de Miguel"
      photo: "/img/FotoSergiodeMiguel.jpeg"
      company: "Universitat de Lleida"
    - name: "Marcos Rodrigues"
      photo: "/img/FotoMarcosRodrigues.jpeg"
      company: "Universitat de Lleida"
    - name: "Jordi Vayreda"
      photo: "/img/FotoJordiVayreda.jpeg"
      company: "Centre de Recerca en Ecologia i Aplicacions Forestals (CREAF)"
